### PR TITLE
Adding region selection to ReutersBridge

### PR DESCRIPTION
**Pull request by Spraynard**
Adding in region selection which in essence changes the `article_uri` parameter. This parameter is used to effectively link back to the region specific Reuters website that contains the article.

### CODE REVIEW

**Comment by csisoap** [comment]
Some API link may not work with the UK edition. Example:

https://wireapi.reuters.com/v8/feed/rapp/us/tabbar/feeds/health <-- Worked with U.S edition

https://wireapi.reuters.com/v8/feed/rapp/uk/tabbar/feeds/health <-- This is not working

EDIT: 
I've just tested all link included with the bridge and noted most of the links worked with U.K edition, except Health (as i mention above), U.S News, China.

**Comment by Spraynard** [comment]
Awesome thank you for testing!

I see what you mean. I don't know if there is a simple fix for coding past that, to get a dynamic selection for available feeds based on region... Seemingly some JS would have to be introduced.

**Comment by csisoap** [comment]
I've just thinked about making each region its own context. For example, like Arte +7 Bridge here:
image

**Comment by Spraynard** [comment]
Oh shoot, you can do that? Dang I will definitely check out that bridge

**Comment by Spraynard** [comment]
This new class should implement a contextual view to differentiate regions.

Feeds that were not available for the UK region have been taken out.

**Comment by csisoap** [comment]
> This new class should implement a contextual view to differentiate regions.
> 
> Feeds that were not available for the UK region have been taken out.

Hi @Spraynard , I've added some new feed specific to U.K edition and make some change to ReutersBridge. You may to check it out right here: https://github.com/Spraynard/rss-bridge/pull/2.

Sorry if i making a mess for you, i'm still noob to GitHub.

**Comment by Spraynard** [comment]
Hey @hollowleviathan thank you for the changes and adding the "Editors Highlight" section to the bridge, it looks nice 🎉 .

I would also recommend to not force push with git unless necessary, as it will cause other developers to have to resolve merge conflicts if they want to work on it as well. If you need help interacting with git a little more then you can def ask me for help.

**Comment by Spraynard** [comment]
Alright I think that we are at a point with this pull request where it can be merged. Let me know if there are any issues.

**Comment by Spraynard** [comment]
Hello! Just wondering if there is anything stopping this commit from being merged? Thanks

**Comment by hollowleviathan** [comment]
Sorry about that, the delay was from the holiday weekend.

**Pull request merged**
