### PR TITLE
Update ReutersBridge.

### PR DESCRIPTION
**Pull request by csisoap**
Sorry for the mess in there.
Here're some new change to Reuters Bridge:

- Remove Pic of the Day section due a lot of images, might not suitable for a RSS feed,
- Modifying function getJson() for mose reusable.
- Add some news sections.
- Fix PHP warning about undeclared index, trying to access null point, etc,......
- Add categories.
- Caption included for each image and move all of them down to the bottom part of the article.

### CODE REVIEW

**Comment by hollowleviathan** [comment]
What's all that other mess? Did you rebase off of the upstream?

**Comment by csisoap** [comment]
Yeah, it's my fault. I'm trying to fork again but since it updated so it included all latest commit in there in case your haven't updated.

**Comment by hollowleviathan** [comment]
I've rebased on the RSS-bridge master, but now you're 3 behind that point. Hopefully this makes it easier to untangle.

**Comment by csisoap** [comment]
Pulling commits from 'master' branch of https://github.com/rss-bridge/rss-bridge to fix CI issue.

**Pull request merged**
